### ISSUE TITLE
Publish only the modified files and replace them in the output folder

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-incremental-builds#11]
1. Detect if a file was changed or not between two transformations
    * Cum facem detectia? MD5, SHA, last-modified
    * Pentru fiecare fisier sa retinem o informatie cand a fost modificat ultima data si sa o stocam pe disk

2. Republish only the modified topics
    Sa detectam care topice au fost modificate si sa le republicam doar pe ele. O sa generam un DITA map temporar sa includa foar fisierele modificate.
    La sfarsitul transformarii, o sa inlocuim in output fisierele noi generate.

**Comment by darwin-s** [comment]
Am implementat transformarea simplificata, cu replace doar la fisierele modificate
