### ISSUE TITLE
Create a cache with all topics from repository and their MD5

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-incremental-builds#13]
Pentru toate topicele care sunt linkate in DITA map o sa le calculam MD5 ca sa putem vedea daca au fost modificate sau nu.

O sa scriem pe disk in directorul de output, intr-un fisier `.cache/filesmd5`, asocierea intre un fisier si md5-ul lui.

**Ce tip de fisiere o sa tinem in cache?** 
Pentru inceput o sa retinem doar DITA topics, cele care sunt linkate in DITA map.

Pentru incarcarea DITA Map-ului am putea sa folosim Xerces-ul.

Ce metoda de serializare a cache-ului folosim?
Dan, te rog gasesti o metoda de serializare.

**Comment by raducoravu** [comment]
Si daca avem topice sau alte resurse de tip imagini, zip-uri, pdf-uri care sunt referite in topice dar nu sunt referinte in map-uri? Sau daca avem submap-uri? DITA Map-uri referite de dita map-ul principal?
Un DITA topic nu se recunoaste dupa extensie (care poate fi si "*.xml"), se recunoaste dupa valoarea atributului @format cu care este referit din topicref.
https://www.oxygenxml.com/dita/1.3/specs/langRef/attributes/theformatattribute.html

**Comment by radu-pisoi** [comment]
> Si daca avem topice sau alte resurse de tip imagini, zip-uri, pdf-uri care sunt referite in topice dar nu sunt referinte in map-uri? Sau daca avem submap-uri? DITA Map-uri referite de dita map-ul principal?

@raducoravu, incercam o implementare progresiva. O sa tratam alte tipuri de resurse mai tarziu.
