### ISSUE TITLE
Update execution to be conform with execution described in "Care este flow-ul de executie al procesului"

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-incremental-builds#22]
Sa modificam executia procesului sa fie conforma cu ce este descris in topicul #21.

As vrea ca fiecare stagiu sa fie logat corespunzator in output, de asemenea sa calculam cat tine un anumit pas si sa logam in output.

**Comment by radu-pisoi** [comment]
La pasul acesta as vrea sa facem si un design la clasele Java care sa se potrivesca flow-ul de executie. @BeniaminSavu poti sa propui tu un design?

**Comment by BeniaminSavu** [comment]
Am adaugat un design cu clasele Java:
![image](https://github.com/oxygenxml-incubator/webhelp-incremental-builds/assets/18349514/924ef4b3-29e8-4ad9-8520-dd49358e5f3d)

Am scris si un "pseudocod" in limbaj natural cu pasii de executie pentru functia main:
```
if(cache exists) {
	// Read the cache from the output folder.
	// Generate the cache for the ditamap. Compute the md5 value for each topicref of the current ditamap.
	// Analyze the 2 caches to detected if we can run a simplified transfromation
	if(we can run simple transformation) {
		// Obtain the list with the modified files.
		// Generate a simplified ditamap file.
		// Run the transformation over the simplified ditamap
		// Replace the files in the output folder.
	} else {
		// Run normal transformation
		// Save the new cache on disk.
	}
} else {
   // Find all topicrefs from the ditamap.
   // Generate the cache. Compute the md5 value for each topicref found
   // Save the cache on disk.
}

```

**Comment by darwin-s** [comment]
Am implementat flow-ul si am facut refactoring la clase si unit teste in conformitate cu diagramele
