### ISSUE TITLE
Generate a temporary DITA map that contains only the modified topics

### ISSUE THREAD

**Issue by BeniaminSavu** [oxygenxml-incubator/webhelp-incremental-builds#25]
Trebuie generat un DITA map temporar care sa contina topicref-uri catre topicele ce au fost modificate dupa compararea hash-ului MD5.

Generarea lui se va face filtrand DITA MAp-ul original si pastrand doar topicele modificate.

Subtasks:

- [ ] #26

**Comment by darwin-s** [comment]
Am adaugat functionalitatea de filtrare a map-ului original si serializarea lui. Filtrarea se face in MapFilter si serializarea momentan se face in CacheManager, dar va fi modificat in urma procesului de refactoring
