### ISSUE TITLE
Create a REST API module

### ISSUE THREAD

**Issue by radu-pisoi** [oxygenxml-incubator/webhelp-incremental-builds#37]
Sa adaugam un modul REST API care sa ne dea informatii despre un DITA map.

API-ul ar trebui sa permita:

1. parsarea/indexarea unui DITA map care va fi identificat dupa un URL

2. obtinerea de informatii generale despre un DITA Map identificat dupa un URL
  - data la care a fost ultima data indexat
  - numarul de topice (optional)
  - titlul

- obtinerea de informatii pentru un topic dintr-un DITA map (DITA Map il identificam prin URL, topicul prin path):
  3. titlu, titluMD5, shortdescMD5
  4. topicele care au cross reference catre el
  5. topicele care au related links catre el
  6. href-ul topic parinte
  7. href topicelor copil

Sa folosim swagger.io pentru definire REST API.

**Comment by Yashmerino** [comment]
Am decis ca sa primim un URL la repository de Git, inloc de URL la un `.ditamap`. Daca primim doar un URL la un `.ditamap` hostat ne complicam foarte mult.

Trebuie sa parsam toate resursele, sa le descarcam local ca la sfarsit sa facem build. Cu un repository e mult mai usor si rapid.
